container: &container
    matrix:
      image: rust:latest
      image: rustlang/rust:nightly

test_task:
  container: *container
  cargo_cache:
    folder: $CARGO_MANIFEST_DIR/target
    fingerprint_script: cat Cargo.lock
  test_script: cargo test

build_task:
  container: *container
  depends_on:
    - test
  cargo_cache:
    folder: $CARGO_MANIFEST_DIR/target
    fingerprint_script: cat Cargo.lock
  build_script: cargo build --release
