matrix: &matrix
  - container:
      image: rust:latest
  - allow_failures: true
    container:
      image: rustlang/rust:nightly

test_task:
  matrix: *matrix
  cargo_cache:
    folder: $CARGO_MANIFEST_DIR/target
    fingerprint_script: cat Cargo.lock
  test_script: cargo test

build_task:
  matrix: *matrix
  cargo_cache:
    folder: $CARGO_MANIFEST_DIR/target
    fingerprint_script: cat Cargo.lock
  build_script: cargo build --release
