strategy:
  matrix:
    linux-stable:
      rustup_toolchain: stable
      imageName: 'ubuntu-16.04'
    linux-nightly:
      rustup_toolchain: nightly
      imageName: 'ubuntu-16.04'
    mac-stable:
      rustup_toolchain: stable
      imageName: 'macos-10.13'
    mac-nightly:
      rustup_toolchain: nightly
      imageName: 'macos-10.13'
    windows-stable:
      rustup_toolchain: stable
      imageName: 'vs2017-win2016'
    windows-nightly:
      rustup_toolchain: nightly
      imageName: 'vs2017-win2016'
      
pool:
  vmImage: $(imageName)

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUSTUP_TOOLCHAIN
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: cargo test --all
    displayName: Cargo test
  - script: cargo build --release
    displayName: Cargo build